/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ignacio.tienda.GUI.Ventanas;

import com.ignacio.tienda.BLL.Comic;
import com.ignacio.tienda.DAL.exception.CodigoRepetidoException;
import javax.swing.JOptionPane;

/**
 *
 * @author ignacio
 */
public class jPIngresoComic extends javax.swing.JPanel {

	/**
	 * Creates new form jPIngresoComic
	 */
	public jPIngresoComic() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize
	 * the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();
        jTF_codigo = new javax.swing.JTextField();
        jB_guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTF_numero = new javax.swing.JTextField();

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jB_guardar.setText("Guardar");
        jB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_numero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jTF_codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB_guardar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jB_guardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarActionPerformed
		try {
			int codigo, numero;
			String nombre;
			String raw_codigo = jTF_codigo.getText();
			String raw_nombre = jTF_nombre.getText();
			String raw_numero = jTF_numero.getText();
			//Comprobaciones
			if (raw_codigo.matches("\\d+")) {
				codigo = Integer.valueOf(raw_codigo);
			} else {
				JOptionPane.showMessageDialog(this,
					"Codigo solo puede tener numeros",
					"Mal formato codigo",
					JOptionPane.WARNING_MESSAGE);
				return;
			}
			if (raw_nombre.matches("[A-Za-z][A-Z a-z]+")) {
				nombre = raw_nombre;
			} else {
				JOptionPane.showMessageDialog(this,
					"Nombre no valido, debe tener formato alfabetico",
					"Nombre no valido",
					JOptionPane.WARNING_MESSAGE);
				return;
			}
			if (raw_numero.matches("\\d+")) {
				numero = Integer.valueOf(raw_numero);
			} else {
				JOptionPane.showMessageDialog(this,
					"Numero solo puede tener numeros",
					"Mal formato codigo",
					JOptionPane.WARNING_MESSAGE);
				return;
			}	//Persistencia
			Comic c = new Comic(codigo, nombre, numero);
			boolean x = c.guardar();
			if (x) {
				JOptionPane.showMessageDialog(this,
					"Comic agregado",
					"Exito",
					JOptionPane.INFORMATION_MESSAGE);
			} else {
				JOptionPane.showMessageDialog(this,
					"Comic no agregado",
					"Falla",
					JOptionPane.ERROR_MESSAGE);
			}
		} catch (CodigoRepetidoException ex) {
			JOptionPane.showMessageDialog(this,
				"El codigo ya esta utilizado",
				"Codigo repetido",
				JOptionPane.ERROR_MESSAGE);
		}

    }//GEN-LAST:event_jB_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTF_codigo;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_numero;
    // End of variables declaration//GEN-END:variables
}
