/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ignacio.tienda.GUI.Ventanas;

import com.ignacio.tienda.BLL.Cliente;
import com.ignacio.tienda.DAL.exception.CodigoRepetidoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ignacio
 */
public class JpIngresoCliente extends javax.swing.JPanel {

	/**
	 * Creates new form JpIngresoCliente
	 */
	public JpIngresoCliente() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_rut = new javax.swing.JTextField();
        jTF_nombre = new javax.swing.JTextField();
        jB_guardar = new javax.swing.JButton();

        jLabel1.setText("Rut");

        jLabel2.setText("Nombre:");

        jB_guardar.setText("Guardar");
        jB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB_guardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(jTF_rut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jB_guardar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_guardarActionPerformed
		String raw_rut = jTF_rut.getText();
		String raw_nombre = jTF_nombre.getText();
		int rut;
		String nombre;
		//Validaciones
		if (raw_rut.matches("\\d{8,9}")) {
			rut = Integer.valueOf(raw_rut);
		} else {
			JOptionPane.showMessageDialog(this, "Inserte un rut valido!",
					"Rut no valido", JOptionPane.WARNING_MESSAGE);
			return;
		}
		if (raw_nombre.matches("[A-Za-z][A-Z a-z]+")) {
			nombre = raw_nombre;
		} else {
			JOptionPane.showMessageDialog(this,
					"Nombre no valido, debe tener formato alfabetico",
					"Nombre no valido",
					JOptionPane.WARNING_MESSAGE);
			return;
		}
		//agregacion
		try {
			Cliente c = new Cliente(rut, nombre);
			boolean s = c.guardar();
			if (s){
			JOptionPane.showMessageDialog(this,
					"Cliente agregado",
					"Exito",
					JOptionPane.INFORMATION_MESSAGE);
			}
		} catch (CodigoRepetidoException ex) {
			JOptionPane.showMessageDialog(this,
					"El rut ingresado ya existe, intente con otro",
					"Rut ya existente",
					JOptionPane.WARNING_MESSAGE);
		}
    }//GEN-LAST:event_jB_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_rut;
    // End of variables declaration//GEN-END:variables
}
