/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ignacio.tienda.GUI.Ventanas;

import com.ignacio.tienda.BLL.Comic;
import com.ignacio.tienda.BLL.VentaBuilder;
import com.ignacio.tienda.DAL.ClienteNoExisteException;
import com.ignacio.tienda.DAL.exception.CodigoRepetidoException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author ignacio
 */
public class JPIngresoVenta extends javax.swing.JPanel {

	ComicsUtil cu;
	ComicsUtil cv;

	/**
	 * Creates new form JPIngresoVenta
	 */
	public JPIngresoVenta() {
		initComponents();
		cu = new ComicsUtil(Comic.getAll());
		cv = new ComicsUtil(new ArrayList<Comic>());
		jL_bodega.setModel(cu);
		jL_compra.setModel(cv);
	}

	/**
	 * This method is called from within the constructor to initialize
	 * the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTF_idVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTF_rut = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_bodega = new javax.swing.JList<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jL_compra = new javax.swing.JList<String>();
        jB_traspaso = new javax.swing.JButton();
        jB_compra = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("ID venta");

        jLabel2.setText("Rut cliente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_idVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                    .addComponent(jTF_rut))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_idVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jLabel3.setText("Productos a comprar:");

        jLabel4.setText("Productos en bodega:");

        jScrollPane1.setViewportView(jL_bodega);

        jScrollPane2.setViewportView(jL_compra);

        jB_traspaso.setText("-->");
        jB_traspaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_traspasoActionPerformed(evt);
            }
        });

        jB_compra.setText("Vender");
        jB_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_compraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jB_compra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addComponent(jB_traspaso)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB_traspaso)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jB_compra)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_traspasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_traspasoActionPerformed
		int index = jL_bodega.getSelectedIndex();
		Comic c = cu.getComic(index);
		cv.add(c);
    }//GEN-LAST:event_jB_traspasoActionPerformed

    private void jB_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_compraActionPerformed
		int idVenta, rut;
		String raw_idVenta = jTF_idVenta.getText();
		String raw_rut = jTF_rut.getText();
		ArrayList<Comic> comics = cv.getAll();
		//Validacion de el id de venta
		if (raw_idVenta.matches("\\d+")) {
			idVenta = Integer.valueOf(raw_idVenta);
		} else {
			JOptionPane.showMessageDialog(this,
				"El id de la venta debe ser un numero",
				"Mal formato en id",
				JOptionPane.WARNING_MESSAGE);
			jTF_idVenta.requestFocus();
			return;
		}
		//Validacion del rut
		if (raw_rut.matches("\\d{8,9}")) {
			rut = Integer.valueOf(raw_rut);
		} else {
			JOptionPane.showMessageDialog(this,
				"El rut no es valido, debe insertar el rut completo "
				+ "sin punto ni guiones",
				"Rut incorrecto",
				JOptionPane.WARNING_MESSAGE);
			jTF_rut.requestFocus();
			return;
		}
		//Validacion de los comics
		if (comics.isEmpty()){
			JOptionPane.showMessageDialog(this,
				"Debe elegir al menos un comic, para la venta",
				"Elija un comic",
				JOptionPane.WARNING_MESSAGE);
			return;
		}
		//Persistencia
		boolean t = false;
		try {
			t = VentaBuilder.crear(idVenta, rut, comics);
		} catch (ClienteNoExisteException ex) {
			JOptionPane.showMessageDialog(this,
				"Cliente no esta registrado",
				"Advertencia",
				JOptionPane.WARNING_MESSAGE);
		} catch (CodigoRepetidoException ex) {
			JOptionPane.showMessageDialog(this,
				"El codigo ya existe, intente con otro",
				"Codigo ya existente",
				JOptionPane.WARNING_MESSAGE);
		}
		if (t) {
			JOptionPane.showMessageDialog(this,
				"Registro guardado con exito",
				"Exito",
				JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this,
				"No se guardo el registro",
				"Error",
				JOptionPane.ERROR_MESSAGE);
		}

    }//GEN-LAST:event_jB_compraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_compra;
    private javax.swing.JButton jB_traspaso;
    private javax.swing.JList<String> jL_bodega;
    private javax.swing.JList<String> jL_compra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTF_idVenta;
    private javax.swing.JTextField jTF_rut;
    // End of variables declaration//GEN-END:variables
}

class ComicsUtil extends AbstractListModel<String> {

	ArrayList<Comic> c;

	public ComicsUtil(ArrayList<Comic> c) {
		this.c = c;
	}

	public void add(Comic c) {
		this.c.add(c);
		this.fireContentsChanged(this, 0, this.c.size());
	}

	public Comic getComic(int index) {
		return this.c.get(index);
	}

	public ArrayList<Comic> getAll() {
		return c;
	}

	@Override
	public int getSize() {
		return c.size();
	}

	@Override
	public String getElementAt(int index) {
		return c.get(index).getNombre();
	}

}
